-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694",
  mode = "3440x1440@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Philips Consumer Electronics Company 34B2U6603 UK02513000694" })
