-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE NE160QDM-NZ6",
  mode = "2560x1600@165.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL P3424WE 6Z926T3",
  mode = "3440x1440@59.97",
  position = "2560x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Dell Inc. DELL P3424WE 6Z926T3" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE NE160QDM-NZ6" })
